# Dependencies
markdown:         redcarpet

redcarpet:
  extensions: ["tables"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Grownups Read Things They Wrote as Kids
tagline:          'Remembering the good, the bad, and the awkward parts of growing up.'
description:      'Remembering the good, the bad, and the awkward parts of growing up. Since 2007.'
url:              https://grownupsreadthingstheywroteaskids.com
baseurl:          ''

author:
  name:           'Dan Misener'
  url:            https://twitter.com/GRTTWaK

paginate:         5
paginate_path:    "/podcast/page:num/"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "episode"

  -
    scope:
        path: "/newsletter/"
    values:
      layout: "page"