# Dependencies
markdown:         kramdown
# redcarpet:
#   extensions: ["tables"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Grownups Read Things They Wrote as Kids
tagline:          'Remembering the good, the bad, and the awkward parts of growing up.'
description:      'Remembering the good, the bad, and the awkward parts of growing up. Since 2007.'
url:              https://grownupsreadthingstheywroteaskids.com
baseurl:          ''
future:           false

author:
  name:           'Dan Misener'
  url:            https://twitter.com/GRTTWaK

paginate:         5
paginate_path:    "/podcast/page:num/"

defaults:
  - scope:
      type: events-upcoming
    values:
      layout: "event"

  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "episode"

  -
    scope:
        path: "/newsletter/"
    values:
      layout: "page"



collections:
  events-upcoming:
    output: true
    permalink: /event/:path/
    # values:
    #     layout: event

# - events-past
#     # output: true
#     # # permalink: /:collection/:path/
#     # permalink: /event/:path/