# Dependencies
markdown:         kramdown
# redcarpet:
#   extensions: ["tables"]

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Grownups Read Things They Wrote as Kids
tagline:          'Remember the good, bad, and awkward parts of growing up.'
description:      'Courageous adults share their childhood and teenage writing — embarrassing diary entries, angsty poetry, bizarre short stories, and more — in front of a room full of strangers. Since 2007.'
url:              https://grownupsreadthingstheywroteaskids.com
baseurl:          ''
future:           false

author:
  name:           'Dan Misener'
  url:            https://twitter.com/GRTTWaK

paginate:         5
paginate_path:    "/podcast/page:num/"





defaults:
  - scope:
      type: events_upcoming
    values:
      layout: "event"

  - scope:
        path: "/newsletter/"
    values:
      layout: "page"

  - scope:
      path: "" # empty string for all files
    values:
      layout: "episode"

collections:
  events_upcoming:
    output: true
    permalink: /event/:slug/
    name: "Upcoming Events"